### @name="Place Order"

POST http://localhost:8080/api/orders
Accept: text/plain
Content-Type: application/json

{
    "customer" : {"email": "roger@adobe.com"},
    "items": [
        {"product": {"id": 2}, "qty": 50}
    ]
}

### @name="Get Orders"

GET http://localhost:8080/api/orders
Accept: application/json