package com.adobe.datarest.repo;


import com.adobe.datarest.entity.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

// for this interface @Repository implementation class is generated by Spring Data JPA
// CREATE, READ, DELETE operations methods are available
// No method for UPDATE
public interface ProductRepo extends JpaRepository<Product, Integer> {
    // Projections
    // select * from products where qty = ?
    List<Product> findByQuantity(int quantity);

    // select * from products where price > ? and quantity = ?
    List<Product> findByPriceGreaterThanAndQuantity(double price, int quantity);

    List<Product> findByPriceBetween(double low, double high);


//    @Query("from Product where price >= :l and price <= :h")
    @Query(value = "select * from products where price >= :l and price <= :h" , nativeQuery = true)
    List<Product> byRange(@Param("l") double low, @Param("h") double high);

    @Modifying
    @Query("update Product  set price = :pr where id = :id")
    void updatePrice(@Param("id") int id, @Param("pr") double price);
}
