package com.adobe.orderapp.repo;

import com.adobe.orderapp.entity.Product;
import org.springframework.data.jpa.repository.JpaRepository;

// for this interface @Repository implementation class is generated by Spring Data JPA
// CREATE, READ, DELETE operations methods are available
// No method for UPDATE
public interface ProductRepo extends JpaRepository<Product, Integer> {
}
