package com.adobe.orderapp.repo;

import com.adobe.orderapp.entity.Product;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

// for this interface @Repository implementation class is generated by Spring Data JPA
// CREATE, READ, DELETE operations methods are available
// No method for UPDATE
public interface ProductRepo extends JpaRepository<Product, Integer> {
    // Projections
    // select * from products where qty = ?
    List<Product> findByQuantity(int quantity);

    // select * from products where price > ? and quantity = ?
    List<Product> findByPriceGreaterThanAndQuantity(double price, int quantity);

    List<Product> findByPriceBetween(double low, double high);
}
